### ISSUE TITLE
snapshots skipped intermittently

### ISSUE THREAD

**Issue by jmichler** [aboovv1976/oci-fss-scheduler#3]
Hi,

I've got a schedule.cfg as follows:
`[ocid1.filesystem.oc1.eu_frankfurt_1.xxxxx] # FSName: PRODApps
Hourly_Snapshot = 1h:1d
Daily_Snapshot =  1d:7d
`
and a crontab as in:
`0 * * * * python3 /u01/install/APPS/oci-fss-scheduler/snapshot-scheduler-tool/fss-snapshot-scheduler.py  >> /u01/install/APPS/oci-fss-scheduler/cron.log 2>&1
`

This leads to some snapshots being missed, see [cron.log](https://github.com/aboovv1976/oci-fss-scheduler/files/9759272/cron.log) attached.
Eventually this is due to minimal jitter in the time? That at the hour when the cronjob runs the hour is not "completely over" so that the tool thinks it does not need another snapshot?
![image](https://user-images.githubusercontent.com/2754419/195184372-b89663bb-9a93-4dc7-a765-723f3d1d2555.png)

**Comment by aboovv1976** [comment]
Thank you for letting me know. I will fix and submit new changes. Sorry for the delay. I was away around the weekend.

**Comment by aboovv1976** [comment]
I added the 0.1% jitter you mentioned. Could you please check if this will work? As you noted, the snapshot API will take variable amount of time to complete.

**Comment by jmichler** [comment]
I guess it is now "more broken":
[oracle@ebscm2 ~]$ python3 /u01/install/APPS/interseroh/oci-fss-scheduler/snapshot-scheduler-tool/fss-snapshot-scheduler.py
  File "/u01/install/APPS/interseroh/oci-fss-scheduler/snapshot-scheduler-tool/fss-snapshot-scheduler.py", line 185
    def around(t)
                ^
SyntaxError: invalid syntax

**Comment by aboovv1976** [comment]
Sorry, forgot a colon. I fixed it, could you pull again? It just a colon at the end of "def around(t)"

**Comment by jmichler** [comment]
Next error:
[oracle@ebscm2 oci-fss-scheduler]$ python3 /u01/install/APPS/xx/oci-fss-scheduler/snapshot-scheduler-tool/fss-snapshot-scheduler.py
2022-10-17T12:43:12.106Z - fss-scheduler - INFO - Creating OCI config file from environment variables failed, error:'OCI_USER_ID' Using default config file
2022-10-17T12:43:12.430Z - fss-scheduler - INFO - FS: PRODApps, Expired snapshot found for hourly_snapshot: hourly_snapshot_2022_10_16-09_00_03, Expired 2022/10/17 09:00:03
2022-10-17T12:43:13.412Z - fss-scheduler - INFO - Deleted Snapshot: hourly_snapshot_2022_10_16-09_00_03
Traceback (most recent call last):
  File "/u01/install/APPS/xx/oci-fss-scheduler/snapshot-scheduler-tool/fss-snapshot-scheduler.py", line 284, in <module>
    if creationRequired(ocid,details['pName'],details["pTime"]):
  File "/u01/install/APPS/xx/oci-fss-scheduler/snapshot-scheduler-tool/fss-snapshot-scheduler.py", line 191, in creationRequired
    if snapshot["created"] >=  around(t):
  File "/u01/install/APPS/xx/oci-fss-scheduler/snapshot-scheduler-tool/fss-snapshot-scheduler.py", line 186, in around
    return t + t * 0.01
TypeError: unsupported operand type(s) for *: 'datetime.datetime' and 'float'

**Comment by aboovv1976** [comment]
please hold.. let me first test it. Apologize for this.

**Comment by aboovv1976** [comment]
I will test it for at least a  few hours and publish it.

**Comment by aboovv1976** [comment]
I submited the fix and tested it for hourly. It seems to be working ok. Thank you.

**Comment by jmichler** [comment]
technically it is working again now, I'll update you in a day or so if we have no more skipped snapshots

**Comment by jmichler** [comment]
Seems fixed now. Thanks

**Comment by jmichler** [comment]
do you happen to be around at cloudworld?

**Comment by aboovv1976** [comment]
I am not in Cloud World :)
